### ISSUE TITLE
Settings in Pebble App fails with "app install unsuccessful. Try again."

### ISSUE THREAD

**Issue by DC-Dave** [joker512/pebble_tracker#1]
Hi, I'm really excited about your app on my pebble time watch. 

The only problem is I am not able to enter settings from the pebble app. I select settings, I see the white rectangle with the red spinning Circle that states "loading settings", but then it fails with "App install unsuccessful. Try again."  I have uninstalled and reloaded the app on the watch to no success.

Is there anything I can do to get your wonderful app running on my Pebble time watch?

Thanks again for developing such a wonderful application!

**Comment by Lertsenem** [comment]
I have the same issue. Any chance you're working on this, joker512? The app looks great and I'm really looking forward using it. :]

**Comment by joker512** [comment]
Hi. Sorry, I wasn't subscripted to notifications and missed this thread.

Can you open this link from your browser?
[Pebble tracker treeview example](https://joker512.github.io/tracker.html?tree=%5B%7B%22text%22%3A%7B%22name%22%3A%22main%22%2C%22value%22%3A%22main%22%7D%2C%22children%22%3A%5B%7B%22text%22%3A%7B%22name%22%3A%22work%22%2C%22value%22%3A%22work%22%7D%2C%22children%22%3A%5B%7B%22text%22%3A%7B%22name%22%3A%22hard%22%2C%22priority%22%3A1%2C%22value%22%3A%22hard%22%7D%7D%2C%7B%22text%22%3A%7B%22name%22%3A%22simple%22%2C%22priority%22%3A1%2C%22value%22%3A%22simple%22%7D%7D%5D%7D%2C%7B%22text%22%3A%7B%22name%22%3A%22education%22%2C%22priority%22%3A2%2C%22value%22%3A%22education%22%7D%7D%5D%7D%2C%7B%22text%22%3A%7B%22name%22%3A%22secondary%22%2C%22value%22%3A%22secondary%22%7D%2C%22children%22%3A%5B%7B%22text%22%3A%7B%22name%22%3A%22additional%22%2C%22value%22%3A%22additional%22%7D%2C%22children%22%3A%5B%7B%22text%22%3A%7B%22name%22%3A%22overview%22%2C%22priority%22%3A3%2C%22value%22%3A%22overview%22%7D%7D%2C%7B%22text%22%3A%7B%22name%22%3A%22optimization%22%2C%22priority%22%3A3%2C%22value%22%3A%22optimization%22%7D%7D%5D%7D%2C%7B%22text%22%3A%7B%22name%22%3A%22distractions%22%2C%22priority%22%3A4%2C%22value%22%3A%22distractions%22%7D%7D%5D%7D%5D)

Pebble settings just opens web page with the similar url, nothing more.

**Comment by Lertsenem** [comment]
The page opens fine on my android browser (chrome).

The crash occurs before any page opens. Is the pebble app trying to open the settings page with a specific browser or with the system browser?

**Comment by joker512** [comment]
It seems that I fixed it. Please, try.
