### ISSUE TITLE
Settings not syncing to watch 

### ISSUE THREAD

**Issue by Atom058** [joker512/pebble_tracker#2]
Hi!

The app seems great so far: good work!

However, my pebble app on android doesn't sync the settings to the watch (i.e. custom category names).

I press the submit button, but the watch app doesn't import the updates.

My config:
OnePlus 3, Android F/W 7.1.1
Pebble Time Steel, F/W 4.3
Pebble Android App, F/W 4.4.1

**Comment by joker512** [comment]
Hi, and thank you for your response!

It seems that the problem exists on Android only. And I've been using iPhone with Pebble for all the time. Can anybody say does this problem occur recently or it exists from the very beginning? And are there any Android users who don't have the issue?

**Comment by joker512** [comment]
I fixed the issue and some others, introduced a new feature and release a new version.
Please, check it.

**Comment by Atom058** [comment]
Hello again!
I checked on my phone/watch again, and your update fixed the problem
Great work, Thank you!
